version: '3'

services:
  elasticsearch:
    image: agordon/elasticsearch:0.0.5-master
    volumes:
      # - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "/usr/share/elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      cluster.initial_master_nodes: master-init
      # cluster.initial_master_nodes: "ip-10-0-2-167.eu-west-1.compute.internal"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    ulimits:
      nofile:
       soft: 65536
       hard: 65536
volumes:
  elasticsearch: